library(pwr)
df = read.csv("/Users/marsh/galvanize/dsi/projects/health_capstone/anova.csv")
names(df) <- c('X','state','year','percent_uninsured')
df$year <- as.factor(df$year)
year_anova <- aov(percent_uninsured ~ year, data = df)
state_anova <- aov(percent_uninsured ~ state, data=df)
summary(year_anova)
pwr.anova.test(k = 9, n = 3192, f=0.05, sig.level=.05)
summary(state_anova)

